In [ ]:
import torch
print(torch.__version__)   ## Checking Version

2.11.0+cpu


In [ ]:
## Now checking the GPU
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available, Using CPU")

GPU not available, Using CPU


## Creating a Tensor

### 1. Creating using Empty

In [ ]:
## Syntax --> .empty(row, column)
tensor = torch.empty(2,3)

In [ ]:
type(tensor)

torch.Tensor

### 2. Creating using Zeros and Ones

In [ ]:
## Syntax .zeros(rows, columns)
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
## Similarly
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### 3. Creating using rand

In [ ]:
## Syntax .rand(rows, columns) --> Random value ranges between 0 and 1
torch.rand(5,6)

tensor([[0.5602, 0.1413, 0.0929, 0.1563, 0.1038, 0.1734],
        [0.0396, 0.7749, 0.6924, 0.1865, 0.3809, 0.3018],
        [0.9069, 0.3881, 0.6869, 0.1379, 0.9171, 0.9331],
        [0.1566, 0.4046, 0.2709, 0.9534, 0.2842, 0.9814],
        [0.9492, 0.9926, 0.7670, 0.9528, 0.2832, 0.2335]])

### 4. Creating using Seed

In [ ]:
torch.manual_seed(100)
torch.rand(5,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784, 0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445, 0.4892, 0.2426, 0.7003]])

### 5. Creating using Tensors

In [ ]:
## Syntax -->torch.tensor(any data type)
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

### 6. Other Ways

In [ ]:
# arange
print(f"Using arange function --> {torch.arange(0, 10)}")

# using linspace
# Syntax .linspace(start, stop, amount)
print(f"Using linspace function ---> {torch.linspace(0,10,10)}")

# using eye
print(f"Using eye function --->{'\n'} {torch.eye(5)}")

# using full
# Syntax .full((rows, columns), number)
print(f"Using full function -->{'\n'} {torch.full((3,3), 5)}")

Using arange function --> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using linspace function ---> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye function --->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full function -->
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensors Shape

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
## If we have to create a tensor of similar shape to a corressponding tensor
torch.empty_like(x)

tensor([[     1191448240, 139739172764912,             256],
        [            128,          290881,              78]])

In [ ]:
## It creates a tensor of Zeros of similar shape to a corressponding tensor
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# Similarly
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

## Tensor Data Types

In [ ]:
## Find Data Type
x.dtype

torch.int64

In [ ]:
## Assign Data Type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
## To convert data type of an existing tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| Datatype                         | Dtype                   | Description                                                                            |
| -------------------------------- | ----------------------- | -------------------------------------------------------------------------------------- |
| 64-bit floating point            | `torch.float64`         | Double-precision floating-point type. Alias: `torch.double`.                           |
| 32-bit floating point            | `torch.float32`         | Standard single-precision floating-point type. Alias: `torch.float`.                   |
| 16-bit floating point            | `torch.float16`         | Half-precision type that reduces memory usage. Alias: `torch.half`.                    |
| 16-bit Brain Floating Point      | `torch.bfloat16`        | Reduced-precision type with a wider numeric range than `float16`.                      |
| 128-bit complex                  | `torch.complex128`      | Complex number containing two 64-bit floating-point values. Alias: `torch.cdouble`.    |
| 64-bit complex                   | `torch.complex64`       | Complex number containing two 32-bit floating-point values. Alias: `torch.cfloat`.     |
| 32-bit complex                   | `torch.complex32`       | Complex number containing two 16-bit floating-point values. Alias: `torch.chalf`.      |
| 64-bit signed integer            | `torch.int64`           | Signed integer commonly used for tensor indices and class labels. Alias: `torch.long`. |
| 32-bit signed integer            | `torch.int32`           | Standard signed integer type. Alias: `torch.int`.                                      |
| 16-bit signed integer            | `torch.int16`           | Signed integer with a range of −32,768 to 32,767. Alias: `torch.short`.                |
| 8-bit signed integer             | `torch.int8`            | Signed integer with a range of −128 to 127.                                            |
| 8-bit unsigned integer           | `torch.uint8`           | Unsigned integer with a range of 0 to 255.                                             |
| 16-bit unsigned integer          | `torch.uint16`          | Unsigned integer with a range of 0 to 65,535; limited operation support.               |
| 32-bit unsigned integer          | `torch.uint32`          | Unsigned 32-bit integer with limited operation support.                                |
| 64-bit unsigned integer          | `torch.uint64`          | Unsigned 64-bit integer with limited operation support.                                |
| Boolean                          | `torch.bool`            | Stores logical values: `True` or `False`.                                              |
| Quantized 8-bit signed integer   | `torch.qint8`           | Signed 8-bit type used for quantized models.                                           |
| Quantized 8-bit unsigned integer | `torch.quint8`          | Unsigned 8-bit type used for quantized models.                                         |
| Quantized 32-bit signed integer  | `torch.qint32`          | Signed 32-bit type used in quantized operations.                                       |
| Quantized 4-bit unsigned integer | `torch.quint4x2`        | Stores two quantized 4-bit unsigned values in one byte.                                |
| Quantized 2-bit unsigned integer | `torch.quint2x4`        | Stores four quantized 2-bit unsigned values in one byte.                               |
| 8-bit floating point (E4M3)      | `torch.float8_e4m3fn`   | Experimental 8-bit floating-point type with four exponent and three mantissa bits.     |
| 8-bit floating point (E5M2)      | `torch.float8_e5m2`     | Experimental 8-bit floating-point type with five exponent and two mantissa bits.       |
| 8-bit floating point (E4M3 FNUZ) | `torch.float8_e4m3fnuz` | Experimental unsigned-zero variant of the E4M3 format.                                 |
| 8-bit floating point (E5M2 FNUZ) | `torch.float8_e5m2fnuz` | Experimental unsigned-zero variant of the E5M2 format.                                 |


## Mathematical Operations on Tensors

### 1. Scaler Operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9535, 0.7064],
        [0.1629, 0.8902]])

In [ ]:
## Addition
add = x + 2
print(f"Adding 2 to all values in a tensor {add}")

## Subtraction
sub = x - 2
print(f"Subtracting 2 to all values in a tensor {sub}")

## Multiplication
mul = x * 3
print(f"Multiplying 3 to all values in a tensor {mul}")

## Division
div = x / 5
print(f"Dividing 5 to all values in a tensor {div}")

## Int Division
a = x * 100
idiv = a // 3

## Mod
mod = idiv % 2

## Power
pow = x ** 2
print(f"Exponent by 2 {pow}")

Adding 2 to all values in a tensor tensor([[2.9535, 2.7064],
        [2.1629, 2.8902]])
Subtracting 2 to all values in a tensor tensor([[-1.0465, -1.2936],
        [-1.8371, -1.1098]])
Multiplying 3 to all values in a tensor tensor([[2.8606, 2.1192],
        [0.4886, 2.6706]])
Dividing 5 to all values in a tensor tensor([[0.1907, 0.1413],
        [0.0326, 0.1780]])
Exponent by 2 tensor([[0.9092, 0.4990],
        [0.0265, 0.7925]])


In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])


In [ ]:
## Add
a + b

## Sub
a - b

## Multiply
a * b

## Division
a / b

## Power
a ** b

tensor([[0.9709, 0.1818, 0.6749],
        [0.5269, 0.6008, 0.6266]])

In [ ]:
c = torch.tensor([1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
## Negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.2, 3.6, 7.2, 5.6])
torch.round(d)

tensor([1., 4., 7., 6.])

In [ ]:
torch.ceil(d)

tensor([2., 4., 8., 6.])

In [ ]:
torch.floor(d)

tensor([1., 3., 7., 5.])

In [ ]:
torch.clamp(d, min=2, max=3)

tensor([2., 3., 3., 3.])

### 2. Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[6., 1., 5.],
        [5., 0., 4.]])

In [ ]:
## sum
torch.sum(e)

tensor(21.)

In [ ]:
## Sum along columns
torch.sum(e, dim=0)

tensor([11.,  1.,  9.])

In [ ]:
## Sum along rows
torch.sum(e, dim=1)

tensor([12.,  9.])

In [ ]:
## Mean
torch.mean(e, dtype=torch.float32)

tensor(3.5000)

In [ ]:
## Mean along columns
torch.mean(e, dtype=torch.float32, dim=0)

tensor([5.5000, 0.5000, 4.5000])

In [ ]:
## Median
torch.median(e)

tensor(4.)

In [ ]:
## Max and Min
torch.max(e)

tensor(6.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
## Product
torch.prod(e)

tensor(0.)

In [ ]:
## STD
torch.std(e)

tensor(2.4290)

In [ ]:
## Variance
torch.var(e)

tensor(5.9000)

In [ ]:
## Argmax
torch.argmax(e)

tensor(0)

In [ ]:
torch.argmin(e)

tensor(4)